// <auto-generated />
using System;
using EMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805144124_BandSalarySeed")]
    partial class BandSalarySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EMS.Domain.Entities.BandSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DearnessAllowance")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntertainmentAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HRA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicalInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BandSalaries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0f318b3-a30f-46c2-9ba3-26051eaa822e"),
                            Band = "E1",
                            BasicSalary = 30000m,
                            ConveyanceAllowance = 2000m,
                            DearnessAllowance = 3000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1000m,
                            HRA = 5000m,
                            MedicalInsurance = 1500m,
                            Stipend = 500m
                        },
                        new
                        {
                            Id = new Guid("4eb2d3e7-4538-4e78-b217-e5a3bfa52d79"),
                            Band = "E2",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1600m,
                            Stipend = 600m
                        },
                        new
                        {
                            Id = new Guid("b9242344-631a-4777-89a3-fd605f268049"),
                            Band = "E3",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1700m,
                            Stipend = 700m
                        },
                        new
                        {
                            Id = new Guid("b46385c1-a711-43df-bb19-7b8f430fa83e"),
                            Band = "E4",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1800m,
                            Stipend = 800m
                        },
                        new
                        {
                            Id = new Guid("baf6893c-e56a-4655-9708-b5a240281e4d"),
                            Band = "E5",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1900m,
                            Stipend = 900m
                        },
                        new
                        {
                            Id = new Guid("54960ba3-2d73-4fed-aed5-76687db263b5"),
                            Band = "E1",
                            BasicSalary = 31000m,
                            ConveyanceAllowance = 2100m,
                            DearnessAllowance = 3100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1100m,
                            HRA = 5100m,
                            MedicalInsurance = 1510m,
                            Stipend = 510m
                        },
                        new
                        {
                            Id = new Guid("ec97ea18-17cc-40ae-bacc-ede3dda78ea1"),
                            Band = "E2",
                            BasicSalary = 36000m,
                            ConveyanceAllowance = 2600m,
                            DearnessAllowance = 3600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1600m,
                            HRA = 5600m,
                            MedicalInsurance = 1610m,
                            Stipend = 610m
                        },
                        new
                        {
                            Id = new Guid("2883b7a1-7caf-4b66-acc1-90b14f2405f1"),
                            Band = "E3",
                            BasicSalary = 41000m,
                            ConveyanceAllowance = 3100m,
                            DearnessAllowance = 4100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2100m,
                            HRA = 6100m,
                            MedicalInsurance = 1710m,
                            Stipend = 710m
                        },
                        new
                        {
                            Id = new Guid("0482c5d2-e7f2-4a34-8039-cb0b82f75841"),
                            Band = "E4",
                            BasicSalary = 46000m,
                            ConveyanceAllowance = 3600m,
                            DearnessAllowance = 4600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2600m,
                            HRA = 6600m,
                            MedicalInsurance = 1810m,
                            Stipend = 810m
                        },
                        new
                        {
                            Id = new Guid("353b546d-fc50-40c3-8d4e-ea0f666c8c8b"),
                            Band = "E5",
                            BasicSalary = 51000m,
                            ConveyanceAllowance = 4100m,
                            DearnessAllowance = 5100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 3100m,
                            HRA = 7100m,
                            MedicalInsurance = 1910m,
                            Stipend = 910m
                        },
                        new
                        {
                            Id = new Guid("1138c8de-6e8b-4ed4-b30a-f12dc6516571"),
                            Band = "E1",
                            BasicSalary = 32000m,
                            ConveyanceAllowance = 2200m,
                            DearnessAllowance = 3200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1200m,
                            HRA = 5200m,
                            MedicalInsurance = 1520m,
                            Stipend = 520m
                        },
                        new
                        {
                            Id = new Guid("8dc90bc1-75f6-40d0-8166-da741b028f4c"),
                            Band = "E2",
                            BasicSalary = 37000m,
                            ConveyanceAllowance = 2700m,
                            DearnessAllowance = 3700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1700m,
                            HRA = 5700m,
                            MedicalInsurance = 1620m,
                            Stipend = 620m
                        },
                        new
                        {
                            Id = new Guid("85dae10c-3320-4a6e-a19f-ed54979da054"),
                            Band = "E3",
                            BasicSalary = 42000m,
                            ConveyanceAllowance = 3200m,
                            DearnessAllowance = 4200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2200m,
                            HRA = 6200m,
                            MedicalInsurance = 1720m,
                            Stipend = 720m
                        },
                        new
                        {
                            Id = new Guid("e4895063-41cf-45a3-bcf1-e3c868b6339c"),
                            Band = "E4",
                            BasicSalary = 47000m,
                            ConveyanceAllowance = 3700m,
                            DearnessAllowance = 4700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2700m,
                            HRA = 6700m,
                            MedicalInsurance = 1820m,
                            Stipend = 820m
                        },
                        new
                        {
                            Id = new Guid("b27b5128-14e8-4056-afe5-5697e48e1c6d"),
                            Band = "E5",
                            BasicSalary = 52000m,
                            ConveyanceAllowance = 4200m,
                            DearnessAllowance = 5200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 3200m,
                            HRA = 7200m,
                            MedicalInsurance = 1920m,
                            Stipend = 920m
                        },
                        new
                        {
                            Id = new Guid("02357dc4-b416-440c-bd93-b9ca4576d06e"),
                            Band = "E1",
                            BasicSalary = 33000m,
                            ConveyanceAllowance = 2300m,
                            DearnessAllowance = 3300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1300m,
                            HRA = 5300m,
                            MedicalInsurance = 1530m,
                            Stipend = 530m
                        },
                        new
                        {
                            Id = new Guid("e738b8f3-4be2-458f-aca4-7586f39b2de0"),
                            Band = "E2",
                            BasicSalary = 38000m,
                            ConveyanceAllowance = 2800m,
                            DearnessAllowance = 3800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1800m,
                            HRA = 5800m,
                            MedicalInsurance = 1630m,
                            Stipend = 630m
                        },
                        new
                        {
                            Id = new Guid("37495332-1b36-4261-af4c-9d72eb03004d"),
                            Band = "E3",
                            BasicSalary = 43000m,
                            ConveyanceAllowance = 3300m,
                            DearnessAllowance = 4300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2300m,
                            HRA = 6300m,
                            MedicalInsurance = 1730m,
                            Stipend = 730m
                        },
                        new
                        {
                            Id = new Guid("b12870be-d090-4d28-8228-a6a02800399d"),
                            Band = "E4",
                            BasicSalary = 48000m,
                            ConveyanceAllowance = 3800m,
                            DearnessAllowance = 4800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2800m,
                            HRA = 6800m,
                            MedicalInsurance = 1830m,
                            Stipend = 830m
                        },
                        new
                        {
                            Id = new Guid("3bd45fc6-55b3-40a5-85e3-a2586f52de53"),
                            Band = "E5",
                            BasicSalary = 53000m,
                            ConveyanceAllowance = 4300m,
                            DearnessAllowance = 5300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 3300m,
                            HRA = 7300m,
                            MedicalInsurance = 1930m,
                            Stipend = 930m
                        },
                        new
                        {
                            Id = new Guid("5488c7d3-32dc-46c2-8edc-73b7bc8336d2"),
                            Band = "E1",
                            BasicSalary = 34000m,
                            ConveyanceAllowance = 2400m,
                            DearnessAllowance = 3400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1400m,
                            HRA = 5400m,
                            MedicalInsurance = 1540m,
                            Stipend = 540m
                        },
                        new
                        {
                            Id = new Guid("98038f4a-c992-424e-835c-5f5e7aba505d"),
                            Band = "E2",
                            BasicSalary = 39000m,
                            ConveyanceAllowance = 2900m,
                            DearnessAllowance = 3900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1900m,
                            HRA = 5900m,
                            MedicalInsurance = 1640m,
                            Stipend = 640m
                        },
                        new
                        {
                            Id = new Guid("5bbd5c90-1512-4f9e-a001-ca77be9bfd02"),
                            Band = "E3",
                            BasicSalary = 44000m,
                            ConveyanceAllowance = 3400m,
                            DearnessAllowance = 4400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2400m,
                            HRA = 6400m,
                            MedicalInsurance = 1740m,
                            Stipend = 740m
                        },
                        new
                        {
                            Id = new Guid("a5626786-1491-44f2-9991-e437e1ce0acb"),
                            Band = "E4",
                            BasicSalary = 49000m,
                            ConveyanceAllowance = 3900m,
                            DearnessAllowance = 4900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2900m,
                            HRA = 6900m,
                            MedicalInsurance = 1840m,
                            Stipend = 840m
                        },
                        new
                        {
                            Id = new Guid("d1d494f0-f826-4d52-83bf-500409946ab1"),
                            Band = "E5",
                            BasicSalary = 54000m,
                            ConveyanceAllowance = 4400m,
                            DearnessAllowance = 5400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 3400m,
                            HRA = 7400m,
                            MedicalInsurance = 1940m,
                            Stipend = 940m
                        },
                        new
                        {
                            Id = new Guid("4a0646c4-df34-461b-8711-1148c545a504"),
                            Band = "E1",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1550m,
                            Stipend = 550m
                        },
                        new
                        {
                            Id = new Guid("e72e3a42-0bac-44ee-95a4-5f94c801e978"),
                            Band = "E2",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1650m,
                            Stipend = 650m
                        },
                        new
                        {
                            Id = new Guid("e09cfed3-6a62-4a43-bb55-2536ac57c588"),
                            Band = "E3",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1750m,
                            Stipend = 750m
                        },
                        new
                        {
                            Id = new Guid("7dc73e18-524a-408e-9fb1-2f0ed7f40219"),
                            Band = "E4",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1850m,
                            Stipend = 850m
                        },
                        new
                        {
                            Id = new Guid("b0ef34fd-d488-441f-b3ae-752c6a8383bd"),
                            Band = "E5",
                            BasicSalary = 55000m,
                            ConveyanceAllowance = 4500m,
                            DearnessAllowance = 5500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3500m,
                            HRA = 7500m,
                            MedicalInsurance = 1950m,
                            Stipend = 950m
                        });
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("GovernmentDocuments");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("GovernmentDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeSalary")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeSalary", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("EmployeeSalary")
                        .IsRequired();

                    b.Navigation("Experiences");

                    b.Navigation("GovernmentDocuments");

                    b.Navigation("Leaves");

                    b.Navigation("PersonalDetails")
                        .IsRequired();

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
