// <auto-generated />
using System;
using EMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240808004316_NullForGD_ExpiryDate")]
    partial class NullForGD_ExpiryDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EMS.Domain.Entities.BandSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DearnessAllowance")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntertainmentAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HRA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicalInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BandSalaries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f3d495a-5179-47c6-8183-20a5998bb913"),
                            Band = "E1",
                            BasicSalary = 30000m,
                            ConveyanceAllowance = 2000m,
                            DearnessAllowance = 3000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1000m,
                            HRA = 5000m,
                            MedicalInsurance = 1500m,
                            Stipend = 500m
                        },
                        new
                        {
                            Id = new Guid("805cbfb4-8604-4da3-9196-2f732f5de2d6"),
                            Band = "E2",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1600m,
                            Stipend = 600m
                        },
                        new
                        {
                            Id = new Guid("3bd0fb5b-b440-48e5-8947-b4812dd674f9"),
                            Band = "E3",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1700m,
                            Stipend = 700m
                        },
                        new
                        {
                            Id = new Guid("cb794f86-21e1-45d4-b71c-6cef84f466f5"),
                            Band = "E4",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1800m,
                            Stipend = 800m
                        },
                        new
                        {
                            Id = new Guid("b32366a1-119d-4810-a7c5-f93b06ae307d"),
                            Band = "E5",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1900m,
                            Stipend = 900m
                        },
                        new
                        {
                            Id = new Guid("809286bf-1e74-4cbe-8fc4-bf8ca3b0cde3"),
                            Band = "E1",
                            BasicSalary = 31000m,
                            ConveyanceAllowance = 2100m,
                            DearnessAllowance = 3100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1100m,
                            HRA = 5100m,
                            MedicalInsurance = 1510m,
                            Stipend = 510m
                        },
                        new
                        {
                            Id = new Guid("895699ea-6d39-42c1-bbfc-3e45329edee8"),
                            Band = "E2",
                            BasicSalary = 36000m,
                            ConveyanceAllowance = 2600m,
                            DearnessAllowance = 3600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1600m,
                            HRA = 5600m,
                            MedicalInsurance = 1610m,
                            Stipend = 610m
                        },
                        new
                        {
                            Id = new Guid("8bfa2454-2b6b-43ca-8b5b-43dc614565a2"),
                            Band = "E3",
                            BasicSalary = 41000m,
                            ConveyanceAllowance = 3100m,
                            DearnessAllowance = 4100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2100m,
                            HRA = 6100m,
                            MedicalInsurance = 1710m,
                            Stipend = 710m
                        },
                        new
                        {
                            Id = new Guid("d2ec559d-feaa-4ca3-9809-bc1691a0c2ce"),
                            Band = "E4",
                            BasicSalary = 46000m,
                            ConveyanceAllowance = 3600m,
                            DearnessAllowance = 4600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2600m,
                            HRA = 6600m,
                            MedicalInsurance = 1810m,
                            Stipend = 810m
                        },
                        new
                        {
                            Id = new Guid("1f05f235-354d-404f-9142-8ff0bb61f476"),
                            Band = "E5",
                            BasicSalary = 51000m,
                            ConveyanceAllowance = 4100m,
                            DearnessAllowance = 5100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 3100m,
                            HRA = 7100m,
                            MedicalInsurance = 1910m,
                            Stipend = 910m
                        },
                        new
                        {
                            Id = new Guid("691f3038-9df4-4601-a858-9b4eacd80a36"),
                            Band = "E1",
                            BasicSalary = 32000m,
                            ConveyanceAllowance = 2200m,
                            DearnessAllowance = 3200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1200m,
                            HRA = 5200m,
                            MedicalInsurance = 1520m,
                            Stipend = 520m
                        },
                        new
                        {
                            Id = new Guid("1ae1d382-fa34-4a41-9b39-29d33302f353"),
                            Band = "E2",
                            BasicSalary = 37000m,
                            ConveyanceAllowance = 2700m,
                            DearnessAllowance = 3700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1700m,
                            HRA = 5700m,
                            MedicalInsurance = 1620m,
                            Stipend = 620m
                        },
                        new
                        {
                            Id = new Guid("9669e225-a259-499f-8d70-928a3526aa01"),
                            Band = "E3",
                            BasicSalary = 42000m,
                            ConveyanceAllowance = 3200m,
                            DearnessAllowance = 4200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2200m,
                            HRA = 6200m,
                            MedicalInsurance = 1720m,
                            Stipend = 720m
                        },
                        new
                        {
                            Id = new Guid("18fc8831-f9df-44d0-9038-9c288d6ff0ab"),
                            Band = "E4",
                            BasicSalary = 47000m,
                            ConveyanceAllowance = 3700m,
                            DearnessAllowance = 4700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2700m,
                            HRA = 6700m,
                            MedicalInsurance = 1820m,
                            Stipend = 820m
                        },
                        new
                        {
                            Id = new Guid("fa8fb68c-f850-418f-8d8d-9eba6ca6d619"),
                            Band = "E5",
                            BasicSalary = 52000m,
                            ConveyanceAllowance = 4200m,
                            DearnessAllowance = 5200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 3200m,
                            HRA = 7200m,
                            MedicalInsurance = 1920m,
                            Stipend = 920m
                        },
                        new
                        {
                            Id = new Guid("fc180e5f-9011-4b44-8245-5903672b4367"),
                            Band = "E1",
                            BasicSalary = 33000m,
                            ConveyanceAllowance = 2300m,
                            DearnessAllowance = 3300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1300m,
                            HRA = 5300m,
                            MedicalInsurance = 1530m,
                            Stipend = 530m
                        },
                        new
                        {
                            Id = new Guid("7b92f247-0ebe-4128-87a8-93d40d2343cd"),
                            Band = "E2",
                            BasicSalary = 38000m,
                            ConveyanceAllowance = 2800m,
                            DearnessAllowance = 3800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1800m,
                            HRA = 5800m,
                            MedicalInsurance = 1630m,
                            Stipend = 630m
                        },
                        new
                        {
                            Id = new Guid("c53a3f98-545e-46b6-b9c8-983594a78e30"),
                            Band = "E3",
                            BasicSalary = 43000m,
                            ConveyanceAllowance = 3300m,
                            DearnessAllowance = 4300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2300m,
                            HRA = 6300m,
                            MedicalInsurance = 1730m,
                            Stipend = 730m
                        },
                        new
                        {
                            Id = new Guid("29f626ef-2dd0-448d-a317-a0d54f4885a7"),
                            Band = "E4",
                            BasicSalary = 48000m,
                            ConveyanceAllowance = 3800m,
                            DearnessAllowance = 4800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2800m,
                            HRA = 6800m,
                            MedicalInsurance = 1830m,
                            Stipend = 830m
                        },
                        new
                        {
                            Id = new Guid("6be2e9ba-7079-4d0d-aa2f-19d95e9abeb4"),
                            Band = "E5",
                            BasicSalary = 53000m,
                            ConveyanceAllowance = 4300m,
                            DearnessAllowance = 5300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 3300m,
                            HRA = 7300m,
                            MedicalInsurance = 1930m,
                            Stipend = 930m
                        },
                        new
                        {
                            Id = new Guid("088197f4-3a4b-40a6-920d-8fe94224d408"),
                            Band = "E1",
                            BasicSalary = 34000m,
                            ConveyanceAllowance = 2400m,
                            DearnessAllowance = 3400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1400m,
                            HRA = 5400m,
                            MedicalInsurance = 1540m,
                            Stipend = 540m
                        },
                        new
                        {
                            Id = new Guid("f8d7ba81-22b0-4a70-9cf1-6bd7d489bac0"),
                            Band = "E2",
                            BasicSalary = 39000m,
                            ConveyanceAllowance = 2900m,
                            DearnessAllowance = 3900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1900m,
                            HRA = 5900m,
                            MedicalInsurance = 1640m,
                            Stipend = 640m
                        },
                        new
                        {
                            Id = new Guid("eaca25ea-c675-4219-a902-d7599abb6b01"),
                            Band = "E3",
                            BasicSalary = 44000m,
                            ConveyanceAllowance = 3400m,
                            DearnessAllowance = 4400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2400m,
                            HRA = 6400m,
                            MedicalInsurance = 1740m,
                            Stipend = 740m
                        },
                        new
                        {
                            Id = new Guid("fd09c1c1-0eb4-44d7-8e91-f8b6ec4cbdd0"),
                            Band = "E4",
                            BasicSalary = 49000m,
                            ConveyanceAllowance = 3900m,
                            DearnessAllowance = 4900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2900m,
                            HRA = 6900m,
                            MedicalInsurance = 1840m,
                            Stipend = 840m
                        },
                        new
                        {
                            Id = new Guid("e47dea8c-b485-4e30-a4fa-52276a7d620a"),
                            Band = "E5",
                            BasicSalary = 54000m,
                            ConveyanceAllowance = 4400m,
                            DearnessAllowance = 5400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 3400m,
                            HRA = 7400m,
                            MedicalInsurance = 1940m,
                            Stipend = 940m
                        },
                        new
                        {
                            Id = new Guid("84ccb4f0-9bd4-443d-a0fc-4347f8efafca"),
                            Band = "E1",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1550m,
                            Stipend = 550m
                        },
                        new
                        {
                            Id = new Guid("a50afa04-b81a-4f16-8aff-9cc57372115e"),
                            Band = "E2",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1650m,
                            Stipend = 650m
                        },
                        new
                        {
                            Id = new Guid("a55a0268-38f5-4f1c-8467-23c0a4dfa436"),
                            Band = "E3",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1750m,
                            Stipend = 750m
                        },
                        new
                        {
                            Id = new Guid("86edf469-3dc0-458d-abde-be0e7deacf0c"),
                            Band = "E4",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1850m,
                            Stipend = 850m
                        },
                        new
                        {
                            Id = new Guid("039f72e1-3db1-47d7-9b71-cae27118165b"),
                            Band = "E5",
                            BasicSalary = 55000m,
                            ConveyanceAllowance = 4500m,
                            DearnessAllowance = 5500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3500m,
                            HRA = 7500m,
                            MedicalInsurance = 1950m,
                            Stipend = 950m
                        });
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("GovernmentDocuments");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("GovernmentDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeSalary")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeSalary", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("EmployeeSalary");

                    b.Navigation("Experiences");

                    b.Navigation("GovernmentDocuments");

                    b.Navigation("Leaves");

                    b.Navigation("PersonalDetails");

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
