// <auto-generated />
using System;
using EMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240806123530_DocumentEnum")]
    partial class DocumentEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EMS.Domain.Entities.BandSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DearnessAllowance")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntertainmentAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HRA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicalInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BandSalaries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28936bc3-a1a1-4cd0-93ca-64953721fe7d"),
                            Band = "E1",
                            BasicSalary = 30000m,
                            ConveyanceAllowance = 2000m,
                            DearnessAllowance = 3000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1000m,
                            HRA = 5000m,
                            MedicalInsurance = 1500m,
                            Stipend = 500m
                        },
                        new
                        {
                            Id = new Guid("c19ffa4b-1edc-46e4-beb5-92f3d6e17325"),
                            Band = "E2",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1600m,
                            Stipend = 600m
                        },
                        new
                        {
                            Id = new Guid("3cb287ed-9905-429e-b5f2-0c56c3ad5f1a"),
                            Band = "E3",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1700m,
                            Stipend = 700m
                        },
                        new
                        {
                            Id = new Guid("cd87a723-3536-409e-8449-eef1994f85f8"),
                            Band = "E4",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1800m,
                            Stipend = 800m
                        },
                        new
                        {
                            Id = new Guid("cca82bac-4b47-4d7c-bca7-953067fb1230"),
                            Band = "E5",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1900m,
                            Stipend = 900m
                        },
                        new
                        {
                            Id = new Guid("7f1e4be4-56c1-41ab-bc15-6c087cced52b"),
                            Band = "E1",
                            BasicSalary = 31000m,
                            ConveyanceAllowance = 2100m,
                            DearnessAllowance = 3100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1100m,
                            HRA = 5100m,
                            MedicalInsurance = 1510m,
                            Stipend = 510m
                        },
                        new
                        {
                            Id = new Guid("f7b96390-4610-4d15-89ae-c92f19e60164"),
                            Band = "E2",
                            BasicSalary = 36000m,
                            ConveyanceAllowance = 2600m,
                            DearnessAllowance = 3600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1600m,
                            HRA = 5600m,
                            MedicalInsurance = 1610m,
                            Stipend = 610m
                        },
                        new
                        {
                            Id = new Guid("14794208-890c-494f-a4c8-7acf82970acd"),
                            Band = "E3",
                            BasicSalary = 41000m,
                            ConveyanceAllowance = 3100m,
                            DearnessAllowance = 4100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2100m,
                            HRA = 6100m,
                            MedicalInsurance = 1710m,
                            Stipend = 710m
                        },
                        new
                        {
                            Id = new Guid("9402a541-1120-4230-8613-b4f1d1ce5578"),
                            Band = "E4",
                            BasicSalary = 46000m,
                            ConveyanceAllowance = 3600m,
                            DearnessAllowance = 4600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2600m,
                            HRA = 6600m,
                            MedicalInsurance = 1810m,
                            Stipend = 810m
                        },
                        new
                        {
                            Id = new Guid("38083aee-df85-45b8-891d-bf900dbdc123"),
                            Band = "E5",
                            BasicSalary = 51000m,
                            ConveyanceAllowance = 4100m,
                            DearnessAllowance = 5100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 3100m,
                            HRA = 7100m,
                            MedicalInsurance = 1910m,
                            Stipend = 910m
                        },
                        new
                        {
                            Id = new Guid("8d550d9b-dabd-4fa9-a666-6a52ec09fa4a"),
                            Band = "E1",
                            BasicSalary = 32000m,
                            ConveyanceAllowance = 2200m,
                            DearnessAllowance = 3200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1200m,
                            HRA = 5200m,
                            MedicalInsurance = 1520m,
                            Stipend = 520m
                        },
                        new
                        {
                            Id = new Guid("3a0879e0-f742-4150-89f7-ab1b63f14b59"),
                            Band = "E2",
                            BasicSalary = 37000m,
                            ConveyanceAllowance = 2700m,
                            DearnessAllowance = 3700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1700m,
                            HRA = 5700m,
                            MedicalInsurance = 1620m,
                            Stipend = 620m
                        },
                        new
                        {
                            Id = new Guid("fd62a570-d7be-45af-972f-dac0665e7b5e"),
                            Band = "E3",
                            BasicSalary = 42000m,
                            ConveyanceAllowance = 3200m,
                            DearnessAllowance = 4200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2200m,
                            HRA = 6200m,
                            MedicalInsurance = 1720m,
                            Stipend = 720m
                        },
                        new
                        {
                            Id = new Guid("559f3494-220c-43f2-8760-526683532d93"),
                            Band = "E4",
                            BasicSalary = 47000m,
                            ConveyanceAllowance = 3700m,
                            DearnessAllowance = 4700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2700m,
                            HRA = 6700m,
                            MedicalInsurance = 1820m,
                            Stipend = 820m
                        },
                        new
                        {
                            Id = new Guid("ac19c131-90a3-40d4-abba-4d6a639b0358"),
                            Band = "E5",
                            BasicSalary = 52000m,
                            ConveyanceAllowance = 4200m,
                            DearnessAllowance = 5200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 3200m,
                            HRA = 7200m,
                            MedicalInsurance = 1920m,
                            Stipend = 920m
                        },
                        new
                        {
                            Id = new Guid("575ad0e7-29b3-4c93-af09-871d92df3ef5"),
                            Band = "E1",
                            BasicSalary = 33000m,
                            ConveyanceAllowance = 2300m,
                            DearnessAllowance = 3300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1300m,
                            HRA = 5300m,
                            MedicalInsurance = 1530m,
                            Stipend = 530m
                        },
                        new
                        {
                            Id = new Guid("f8e4dc0c-a0a6-46d3-a0a1-706e800cdf7c"),
                            Band = "E2",
                            BasicSalary = 38000m,
                            ConveyanceAllowance = 2800m,
                            DearnessAllowance = 3800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1800m,
                            HRA = 5800m,
                            MedicalInsurance = 1630m,
                            Stipend = 630m
                        },
                        new
                        {
                            Id = new Guid("10f9c4a2-2a64-459a-949a-919e18ac4e44"),
                            Band = "E3",
                            BasicSalary = 43000m,
                            ConveyanceAllowance = 3300m,
                            DearnessAllowance = 4300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2300m,
                            HRA = 6300m,
                            MedicalInsurance = 1730m,
                            Stipend = 730m
                        },
                        new
                        {
                            Id = new Guid("6cd600c4-fe1c-48d4-934c-ac6f8926e2f9"),
                            Band = "E4",
                            BasicSalary = 48000m,
                            ConveyanceAllowance = 3800m,
                            DearnessAllowance = 4800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2800m,
                            HRA = 6800m,
                            MedicalInsurance = 1830m,
                            Stipend = 830m
                        },
                        new
                        {
                            Id = new Guid("6b9d76d1-c195-4b0c-9d39-e651553a4140"),
                            Band = "E5",
                            BasicSalary = 53000m,
                            ConveyanceAllowance = 4300m,
                            DearnessAllowance = 5300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 3300m,
                            HRA = 7300m,
                            MedicalInsurance = 1930m,
                            Stipend = 930m
                        },
                        new
                        {
                            Id = new Guid("578d5995-b575-42de-b011-7fe7fdd11be4"),
                            Band = "E1",
                            BasicSalary = 34000m,
                            ConveyanceAllowance = 2400m,
                            DearnessAllowance = 3400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1400m,
                            HRA = 5400m,
                            MedicalInsurance = 1540m,
                            Stipend = 540m
                        },
                        new
                        {
                            Id = new Guid("c9ea2f0c-02ea-4e21-8baa-984184e904ec"),
                            Band = "E2",
                            BasicSalary = 39000m,
                            ConveyanceAllowance = 2900m,
                            DearnessAllowance = 3900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1900m,
                            HRA = 5900m,
                            MedicalInsurance = 1640m,
                            Stipend = 640m
                        },
                        new
                        {
                            Id = new Guid("90d552c6-ce4f-43dc-adaf-e12d18f7cc97"),
                            Band = "E3",
                            BasicSalary = 44000m,
                            ConveyanceAllowance = 3400m,
                            DearnessAllowance = 4400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2400m,
                            HRA = 6400m,
                            MedicalInsurance = 1740m,
                            Stipend = 740m
                        },
                        new
                        {
                            Id = new Guid("eafb488a-c3ff-449d-8a4d-7f8c1d7bf839"),
                            Band = "E4",
                            BasicSalary = 49000m,
                            ConveyanceAllowance = 3900m,
                            DearnessAllowance = 4900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2900m,
                            HRA = 6900m,
                            MedicalInsurance = 1840m,
                            Stipend = 840m
                        },
                        new
                        {
                            Id = new Guid("29a1d0aa-00e5-497a-869f-efba8aa7ac37"),
                            Band = "E5",
                            BasicSalary = 54000m,
                            ConveyanceAllowance = 4400m,
                            DearnessAllowance = 5400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 3400m,
                            HRA = 7400m,
                            MedicalInsurance = 1940m,
                            Stipend = 940m
                        },
                        new
                        {
                            Id = new Guid("0f6161c8-4be8-4f08-881a-cd4fdf1a22aa"),
                            Band = "E1",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1550m,
                            Stipend = 550m
                        },
                        new
                        {
                            Id = new Guid("543f694a-f04e-4c61-b4d5-76a58822d01b"),
                            Band = "E2",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1650m,
                            Stipend = 650m
                        },
                        new
                        {
                            Id = new Guid("1bd8605d-cae2-4d16-b96f-79c275ccb13c"),
                            Band = "E3",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1750m,
                            Stipend = 750m
                        },
                        new
                        {
                            Id = new Guid("cb119bd5-95e0-4aa4-8899-e9c645779606"),
                            Band = "E4",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1850m,
                            Stipend = 850m
                        },
                        new
                        {
                            Id = new Guid("84c96b3a-56fc-4d9c-8229-94d9a341c989"),
                            Band = "E5",
                            BasicSalary = 55000m,
                            ConveyanceAllowance = 4500m,
                            DearnessAllowance = 5500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3500m,
                            HRA = 7500m,
                            MedicalInsurance = 1950m,
                            Stipend = 950m
                        });
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("GovernmentDocuments");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("GovernmentDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeSalary")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeSalary", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("EmployeeSalary");

                    b.Navigation("Experiences");

                    b.Navigation("GovernmentDocuments");

                    b.Navigation("Leaves");

                    b.Navigation("PersonalDetails");

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
