// <auto-generated />
using System;
using EMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805112017_BandSalarySeed")]
    partial class BandSalarySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EMS.Domain.Entities.BandSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DearnessAllowance")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntertainmentAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HRA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicalInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BandSalaries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a2bd1f6-ccd8-43d9-a68c-a578427cc934"),
                            Band = "E1",
                            BasicSalary = 30000m,
                            ConveyanceAllowance = 2000m,
                            DearnessAllowance = 3000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1000m,
                            HRA = 5000m,
                            MedicalInsurance = 1500m,
                            Stipend = 500m
                        },
                        new
                        {
                            Id = new Guid("129f0f4b-5bf8-4633-8dd3-9cee8830b347"),
                            Band = "E2",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1600m,
                            Stipend = 600m
                        },
                        new
                        {
                            Id = new Guid("a6256f03-db30-45d1-ac9b-9b7c20e48552"),
                            Band = "E3",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1700m,
                            Stipend = 700m
                        },
                        new
                        {
                            Id = new Guid("d99405cd-1462-4f85-8f63-ea9778fd7b0b"),
                            Band = "E4",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1800m,
                            Stipend = 800m
                        },
                        new
                        {
                            Id = new Guid("fc17d898-70d0-491b-ae50-f397c9743629"),
                            Band = "E5",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 0,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1900m,
                            Stipend = 900m
                        },
                        new
                        {
                            Id = new Guid("daecc282-80c2-4c2e-80d6-457ac6ce0833"),
                            Band = "E1",
                            BasicSalary = 31000m,
                            ConveyanceAllowance = 2100m,
                            DearnessAllowance = 3100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1100m,
                            HRA = 5100m,
                            MedicalInsurance = 1510m,
                            Stipend = 510m
                        },
                        new
                        {
                            Id = new Guid("98537331-45b4-4ed9-a74d-a130036f1747"),
                            Band = "E2",
                            BasicSalary = 36000m,
                            ConveyanceAllowance = 2600m,
                            DearnessAllowance = 3600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 1600m,
                            HRA = 5600m,
                            MedicalInsurance = 1610m,
                            Stipend = 610m
                        },
                        new
                        {
                            Id = new Guid("9272d969-c283-4e92-b819-030ca74962d7"),
                            Band = "E3",
                            BasicSalary = 41000m,
                            ConveyanceAllowance = 3100m,
                            DearnessAllowance = 4100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2100m,
                            HRA = 6100m,
                            MedicalInsurance = 1710m,
                            Stipend = 710m
                        },
                        new
                        {
                            Id = new Guid("2b9367f0-bd76-488a-9751-62d57fd62ef0"),
                            Band = "E4",
                            BasicSalary = 46000m,
                            ConveyanceAllowance = 3600m,
                            DearnessAllowance = 4600m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 2600m,
                            HRA = 6600m,
                            MedicalInsurance = 1810m,
                            Stipend = 810m
                        },
                        new
                        {
                            Id = new Guid("01fd65db-a5e0-405f-ac1a-b4c0fa3b1cd4"),
                            Band = "E5",
                            BasicSalary = 51000m,
                            ConveyanceAllowance = 4100m,
                            DearnessAllowance = 5100m,
                            DepartmentType = 1,
                            EntertainmentAllowance = 3100m,
                            HRA = 7100m,
                            MedicalInsurance = 1910m,
                            Stipend = 910m
                        },
                        new
                        {
                            Id = new Guid("c868b234-76a6-4a45-afc2-e9bc0517b3cd"),
                            Band = "E1",
                            BasicSalary = 32000m,
                            ConveyanceAllowance = 2200m,
                            DearnessAllowance = 3200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1200m,
                            HRA = 5200m,
                            MedicalInsurance = 1520m,
                            Stipend = 520m
                        },
                        new
                        {
                            Id = new Guid("cc3427b2-d22a-4b54-ae3d-32bc306f9fbb"),
                            Band = "E2",
                            BasicSalary = 37000m,
                            ConveyanceAllowance = 2700m,
                            DearnessAllowance = 3700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 1700m,
                            HRA = 5700m,
                            MedicalInsurance = 1620m,
                            Stipend = 620m
                        },
                        new
                        {
                            Id = new Guid("5684586c-de7d-476f-8aca-c776ff2d5716"),
                            Band = "E3",
                            BasicSalary = 42000m,
                            ConveyanceAllowance = 3200m,
                            DearnessAllowance = 4200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2200m,
                            HRA = 6200m,
                            MedicalInsurance = 1720m,
                            Stipend = 720m
                        },
                        new
                        {
                            Id = new Guid("f5bb4088-dcd7-47c4-8e30-71656eb7cc00"),
                            Band = "E4",
                            BasicSalary = 47000m,
                            ConveyanceAllowance = 3700m,
                            DearnessAllowance = 4700m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 2700m,
                            HRA = 6700m,
                            MedicalInsurance = 1820m,
                            Stipend = 820m
                        },
                        new
                        {
                            Id = new Guid("a93efd29-172c-48f1-9839-cc4a15f6be4a"),
                            Band = "E5",
                            BasicSalary = 52000m,
                            ConveyanceAllowance = 4200m,
                            DearnessAllowance = 5200m,
                            DepartmentType = 2,
                            EntertainmentAllowance = 3200m,
                            HRA = 7200m,
                            MedicalInsurance = 1920m,
                            Stipend = 920m
                        },
                        new
                        {
                            Id = new Guid("240f6a36-6b4f-4c31-a809-cb6ae903e16b"),
                            Band = "E1",
                            BasicSalary = 33000m,
                            ConveyanceAllowance = 2300m,
                            DearnessAllowance = 3300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1300m,
                            HRA = 5300m,
                            MedicalInsurance = 1530m,
                            Stipend = 530m
                        },
                        new
                        {
                            Id = new Guid("7f4c20f0-7d85-4121-9d59-f799d4be9275"),
                            Band = "E2",
                            BasicSalary = 38000m,
                            ConveyanceAllowance = 2800m,
                            DearnessAllowance = 3800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 1800m,
                            HRA = 5800m,
                            MedicalInsurance = 1630m,
                            Stipend = 630m
                        },
                        new
                        {
                            Id = new Guid("28351979-df06-4fb2-a3d3-920ded00a1bc"),
                            Band = "E3",
                            BasicSalary = 43000m,
                            ConveyanceAllowance = 3300m,
                            DearnessAllowance = 4300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2300m,
                            HRA = 6300m,
                            MedicalInsurance = 1730m,
                            Stipend = 730m
                        },
                        new
                        {
                            Id = new Guid("f3e14d57-4005-418e-9dda-15f5f9f2c2ff"),
                            Band = "E4",
                            BasicSalary = 48000m,
                            ConveyanceAllowance = 3800m,
                            DearnessAllowance = 4800m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 2800m,
                            HRA = 6800m,
                            MedicalInsurance = 1830m,
                            Stipend = 830m
                        },
                        new
                        {
                            Id = new Guid("01bb09ee-9626-4684-8ead-1b8178ec73bd"),
                            Band = "E5",
                            BasicSalary = 53000m,
                            ConveyanceAllowance = 4300m,
                            DearnessAllowance = 5300m,
                            DepartmentType = 3,
                            EntertainmentAllowance = 3300m,
                            HRA = 7300m,
                            MedicalInsurance = 1930m,
                            Stipend = 930m
                        },
                        new
                        {
                            Id = new Guid("e57b40cb-57d8-4c1e-bac5-bcb945345c64"),
                            Band = "E1",
                            BasicSalary = 34000m,
                            ConveyanceAllowance = 2400m,
                            DearnessAllowance = 3400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1400m,
                            HRA = 5400m,
                            MedicalInsurance = 1540m,
                            Stipend = 540m
                        },
                        new
                        {
                            Id = new Guid("756a4d95-f696-48ab-aab3-f3c6760ebf42"),
                            Band = "E2",
                            BasicSalary = 39000m,
                            ConveyanceAllowance = 2900m,
                            DearnessAllowance = 3900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 1900m,
                            HRA = 5900m,
                            MedicalInsurance = 1640m,
                            Stipend = 640m
                        },
                        new
                        {
                            Id = new Guid("7affa64d-da13-4e89-8c8f-6001c51f75fa"),
                            Band = "E3",
                            BasicSalary = 44000m,
                            ConveyanceAllowance = 3400m,
                            DearnessAllowance = 4400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2400m,
                            HRA = 6400m,
                            MedicalInsurance = 1740m,
                            Stipend = 740m
                        },
                        new
                        {
                            Id = new Guid("615af6cb-4e7c-48c4-a8ae-2fe8fea15bc6"),
                            Band = "E4",
                            BasicSalary = 49000m,
                            ConveyanceAllowance = 3900m,
                            DearnessAllowance = 4900m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 2900m,
                            HRA = 6900m,
                            MedicalInsurance = 1840m,
                            Stipend = 840m
                        },
                        new
                        {
                            Id = new Guid("fe27c431-f69d-4a7a-8952-93b0bf07afeb"),
                            Band = "E5",
                            BasicSalary = 54000m,
                            ConveyanceAllowance = 4400m,
                            DearnessAllowance = 5400m,
                            DepartmentType = 4,
                            EntertainmentAllowance = 3400m,
                            HRA = 7400m,
                            MedicalInsurance = 1940m,
                            Stipend = 940m
                        },
                        new
                        {
                            Id = new Guid("57d19cd0-6fd5-4fe7-b6de-0afde371a595"),
                            Band = "E1",
                            BasicSalary = 35000m,
                            ConveyanceAllowance = 2500m,
                            DearnessAllowance = 3500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 1500m,
                            HRA = 5500m,
                            MedicalInsurance = 1550m,
                            Stipend = 550m
                        },
                        new
                        {
                            Id = new Guid("1e237a41-5d18-49d0-93b6-ded9c7170f46"),
                            Band = "E2",
                            BasicSalary = 40000m,
                            ConveyanceAllowance = 3000m,
                            DearnessAllowance = 4000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2000m,
                            HRA = 6000m,
                            MedicalInsurance = 1650m,
                            Stipend = 650m
                        },
                        new
                        {
                            Id = new Guid("7549db0f-b0e5-4ced-9118-5a7f2a999dbd"),
                            Band = "E3",
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 3500m,
                            DearnessAllowance = 4500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 2500m,
                            HRA = 6500m,
                            MedicalInsurance = 1750m,
                            Stipend = 750m
                        },
                        new
                        {
                            Id = new Guid("4f3ae2a7-cf5e-4c18-b15d-17327afd138d"),
                            Band = "E4",
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 4000m,
                            DearnessAllowance = 5000m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3000m,
                            HRA = 7000m,
                            MedicalInsurance = 1850m,
                            Stipend = 850m
                        },
                        new
                        {
                            Id = new Guid("741ff499-8f48-41bb-bc2d-93e0f593bf4e"),
                            Band = "E5",
                            BasicSalary = 55000m,
                            ConveyanceAllowance = 4500m,
                            DearnessAllowance = 5500m,
                            DepartmentType = 5,
                            EntertainmentAllowance = 3500m,
                            HRA = 7500m,
                            MedicalInsurance = 1950m,
                            Stipend = 950m
                        });
                });

            modelBuilder.Entity("EMS.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("GovernmentDocuments");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeType", b =>
                {
                    b.Property<Guid>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.Domain.Entities.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Certification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Experience", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.GovernmentDocument", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("GovernmentDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeDetails.PersonalDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeDetails.Qualification", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeSalary")
                        .HasForeignKey("EMS.Domain.Entities.EmployeeSalary", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Leave", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Report", b =>
                {
                    b.HasOne("EMS.Domain.Entities.Department", "Department")
                        .WithMany("Reports")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("EMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("EmployeeSalary")
                        .IsRequired();

                    b.Navigation("Experiences");

                    b.Navigation("GovernmentDocuments");

                    b.Navigation("Leaves");

                    b.Navigation("PersonalDetails")
                        .IsRequired();

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("EMS.Domain.Entities.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
